### ISSUE TITLE
A way to know which nodes are matched in a search

### ISSUE THREAD

**Issue by apatrida** [burtcorp/jmespath-java#30]
I am porting a JSON transformation library over to JMESPath, or I would like to.  Is there any way to know when you do a search, which nodes matched (instead of returning the values, return the paths to the nodes; or both)?

I use this to basically implement a select => transform => apply(update/insert/delete) and that pattern needs to know the source paths so that it can handle relative paths on the targeting side.

**Comment by apatrida** [comment]
looks like I would need to add this as a trace functionality, will see what the consequences of that are.

**Comment by iconara** [comment]
Currently there is no such functionality. You can probably achieve it, but only with a lot of work. It's possible to create a custom adapter/runtime that creates a custom node factory that creates custom AST nodes (or wraps the standard AST nodes) that somehow recorded what was passed to `Node#search(T input)` for every invocation, but I'm not sure it would be exactly what you want. It would be really hard to do it without having to keep the state in the AST nodes, which would mean further complications with thread safety and so on.

Maybe in the future we'll have to change what `Node#search(T input)` from `T` to some kind of container of `T` so that you can attach information to the result. IIRC we've had another use case for something like that.

**Comment by apatrida** [comment]
I'm trying a `Node#search(T input, Trace pathTrace)` approach now that records the tree of successful paths and reduces it to a text version of the node paths at the end to see how it works.  All fun!

**Comment by apatrida** [comment]
I'll report back.

**Comment by apatrida** [comment]
Ok, I have the basics working, just need to handle forks in the tree to build mulitple paths efficiently, but its close and wasn't too bad.

**Comment by apatrida** [comment]
ah, hard part is knowing when to pop back up my stack.  hmmmmmm

**Comment by apatrida** [comment]
ok, got it.  Just filling it in correctly for each node type.  Cool.  I'll do a PR based off of your other branch when done.

**Comment by apatrida** [comment]
Test:
```
Records[*].responseElements.instancesSet.items[*].instanceId
```

Results in traces:

```
Records[1].responseElements.instancesSet.items[1].instanceId, Records[2].responseElements.instancesSet.items[1].instanceId
```

**Comment by apatrida** [comment]
@iconara I have tracing for nodes/properties/projections ... and can add it for other things, but not sure how useful that is other than for debugging.  Also I don't trace through pipes, but could start a new trace after if we really want a debugging or programmatic trace all the way through.  Any thoughts before I wrap this up?

**Comment by iconara** [comment]
@apatrida I will be traveling this and next week and probably won’t have much time to look at anything unfortunately. However, it would be good to know more about what you had to do to add this tracing, since, as you say, if it’s not generally useful it might not be something we can merge.
