### ISSUE TITLE
Query works in js version but not returning expected output in java library

### ISSUE THREAD

**Issue by harshvardhanv** [burtcorp/jmespath-java#34]
The following expression evaluates correctly in the JS version of JmesPath. But the same expression returns an empty array in the Java version
 
EXPRESSION
```
[?(properties[?(id == 'LowerLimitAlarm')].value) >= (properties[?(id == 'UpperLimitAlarm')].value)]
```
 
JSON
```json
[
  {
    "name": "WRONG TAG equal threshold",
    "properties": [
      {
        "id": "LowerLimitAlarm",
        "value": [
          100
        ],
        "type": "int"
      },
      {
        "id": "UpperLimitAlarm",
        "value": [
          100
        ],
        "type": "int"
      }
    ]
  },
  {
    "name": "WRONG TAG2 mismatched thresholds",
    "properties": [
      {
        "id": "LowerLimitAlarm",
        "value": [
          13
        ],
        "type": "int"
      },
      {
        "id": "UpperLimitAlarm",
        "value": [
          12
        ],
        "type": "int"
      }
    ]
  },
  {
    "name": "asset7 tag3",
    "properties": [
      {
        "id": "LowerLimitAlarm",
        "value": [
          10
        ],
        "type": "int"
      },
      {
        "id": "UpperLimitAlarm",
        "value": [
          21
        ],
        "type": "int"
      }
    ]
  },
  {
    "name": "asset7 tag4",
    "properties": [
      {
        "id": "LowerLimitAlarm",
        "value": [
          113
        ],
        "type": "int"
      },
      {
        "id": "UpperLimitAlarm",
        "value": [
          210
        ],
        "type": "int"
      }
    ]
  }
]
```

EXPECTED OUTPUT (can be obtained from js version)
```json
[
  {
    "name": "WRONG TAG equal threshold",
    "properties": [
      {
        "id": "LowerLimitAlarm",
        "value": [
          100
        ],
        "type": "int"
      },
      {
        "id": "UpperLimitAlarm",
        "value": [
          100
        ],
        "type": "int"
      }
    ]
  },
  {
    "name": "WRONG TAG2 mismatched thresholds",
    "properties": [
      {
        "id": "LowerLimitAlarm",
        "value": [
          13
        ],
        "type": "int"
      },
      {
        "id": "UpperLimitAlarm",
        "value": [
          12
        ],
        "type": "int"
      }
    ]
  }
]
```

**Comment by iconara** [comment]
Thank you for reporting this. I will take a look, but I can't promise I'll have enough time to fix it anytime soon. This project hasn't been very prioritised lately unfortunately.

**Comment by iconara** [comment]
Looking at it closer I'm not sure the JavaScript implementation is really doing the right thing here. `properties[?(id == 'LowerLimitAlarm')].value` looks like it would evaluate to for example `[100]` (or even `[[100]]`, because IIRC `[?…]` always evaluates to a list), which is not a number (and comparison operators except for `==` and `!=` are not defined for other types than numbers).

Consider the expression `[?properties[?id == 'LowerLimitAlarm'].value >= [100]]`, this should be what one of the comparisons should be if we evaluate the right hand side by hand, correct? That should return an empty list because `>=` is defined to result in `null` when one of the operands is not a number. However, the JavaScript demo on jmespath.org returns all objects, even those where the comparison would be for example `[13] >= [100]` if we evaluate both sides by hand.

I might be wrong with this, it's really tricky to debug JMESPath, but right now it looks to me like the JavaScript implementation is doing something strange that shouldn't work.
