### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by slandelle** [burtcorp/jmespath-java#41]
Hello,

Sorry to bug you, but could you please advertise if this project is still active or dead?
Latest releases didn't properly make it to maven central, and there hasn't been any answer to issues and pull requests for one year.

This project is a great piece of software and next [Gatling](https://gatling.io/) release will use it so I'm willing to lend a hand maintaining it.

Looking forward to reading from you.

Regards,

Stéphane

**Comment by iconara** [comment]
Sorry for not responding sooner. I didn't see the notification from your initial PR because it ended up in the same flood as the PR discussions for our internal repos.

The project isn't dead, but as you can see hardly in active development. We built it a couple of years ago to solve a problem, and besides some fixes we haven't had any need to change it, and it hasn't seen very much use outside of our company.

I'm very happy to hear that you're using it, and I'm available to help out if you need me. PRs are very welcome, and if things work out I would be happy to add you as an owner of the repo eventually. The ones you opened so far were much appreciated.

Please request reviews from me on future PRs, that way there's a better chance of me actually seeing them.

**Comment by slandelle** [comment]
Thanks a lot Theo!
Gatling currently supports [JsonPath](https://goessner.net/articles/JsonPath/). We have our own implementation (in Scala).
The core issue with JsonPath is the total lack of a proper spec and TCK, so there are tons implementations out there (a Java one got its hands on the Github organization while a JS one got the domain name), each with its own bugs and interpretation, making things super confusing for the users.

JMESPath fits here nicely as it has a well defined syntax. The only lacking thing IMHO is the lack of recursive traversal (a la `//` in XPath and `..` in JsonPath), but aside this, it's super powerful.

We'll ship your implementation in our next minor release (this summer) and advertise it, so hopefully it will bring it more attention.

I plan on building a JMH benchmark suite and do some profiling, so I expect to be able to contribute some perf improvements in the next weeks.

Thanks a lot for this cool project!

**Comment by iconara** [comment]
Thank you, and good luck.
