### ISSUE TITLE
Consider reverting Adapter::getProperty(T value, T name)

### ISSUE THREAD

**Issue by slandelle** [burtcorp/jmespath-java#51]
I'm sorry to ask this way but I don't know any other way to reach out and ask questions.
Please let me know if I can reach out with another means.

d2e1bff925d6e6787785308896f46f7f50b56a83 deprecated `Adapter::getProperty(T value, String name)` and introduced `Adapter::getProperty(T value, T name)`.

This commit causes extra allocations in JacksonRuntime and GsonRuntime (respectively TextNode and JsonPrimitive), typically in getPropertyNames.

This change was for the sake of introducing a JRuby runtime. Commit was almost 3 years ago and it seems this runtime never made it.
IMHO, it would make sense to revert this change.

WDYT?

**Comment by iconara** [comment]
Thank you for the latest slew of PRs, they all look good. Thanks for spending the time dusting off things in this project.

I don't remember everything about what I was doing three years ago, but I remember that when I started looking into a more left-field adapter like the JRuby adapter I realised I had made a few bad assumptions, and one of them was that property names would always be `String`.

If you can figure out a way for the `Adapter::getProperty(T value, String name)` and `Adapter::getProperty(T value, T name)` to co-exist, so that implementations where properties are always strings can use the former and others implement the latter I definitely wouldn't mind removing the deprecation.

Otherwise I think I would like to see some hard numbers on what kind of overhead we are talking about.

**Comment by iconara** [comment]
Opening issues like this to discuss feature requests and ideas works for me, btw. If you want to talk more privately for some reason you can email me at the address found in the git logs.

I merged some of your PRs, but there were two where I had some minor things I wanted you to fix first. I accidentally approved them (I do approve of them, but I try to only use that when I don't have any more comments).

**Comment by iconara** [comment]
I've looked more closely now at the commit you link to, and to me it looks like it is only creating extra allocations at expression compile time. To me, compilation has not been an important optimisation target, and in fact I've gone to some lengths to ensure that as much as possible is done during compilation to make executions faster. The reason is that you're expected to cache expressions if you are worried about performance. If all executions are preceded by a compilation I don't think that an allocation here or there is going to be a problem, it's going to be swamped by everything else that happens during compilation. Am I missing something?

**Comment by slandelle** [comment]
You're mostly right, indeed.
* `getProperty` is only called from `PropertyNode` but the key is computed once, so you're fine as long as you cache the compiled expression
* `getPropertyNames` is called from `KeyFunction` and `MergeFunction` but you need nodes to create an array anyway.

The only things that is on lots of runtime paths is `BaseRuntime::deepEqualsObject` which is called from `BaseRuntime::compare` which is in turn called from `ComparisonNode` and all the comparison based functions every time you want to apply on an array node.
Not sure it's a common use case though.

**Comment by iconara** [comment]
@slandelle how do you feel about this issue? Can I close it or do you still feel that it needs to be resolved?

**Comment by slandelle** [comment]
> I've looked more closely now at the commit you link to, and to me it looks like it is only creating extra allocations at expression compile time.

You're right, and I agree compilation is usually not on the hot path.
Closing, thanks!
